In [4]:
from google.colab import files

uploaded = files.upload()

Saving FIFA_WorldCup_2026_Analytics_Full_Structure.zip to FIFA_WorldCup_2026_Analytics_Full_Structure.zip

In [5]:
import zipfile

zip_path = "FIFA_WorldCup_2026_Analytics_Full_Structure.zip"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall("FIFA_Data")

In [6]:
import os

print(os.listdir("FIFA_Data"))

['sql', '.gitignore', 'notebooks', 'assets', 'requirements.txt', 'dashboard', 'data', 'README.md', 'scripts', 'gui', 'screenshots']

In [11]:
folder = "FIFA_Data/data/raw"

In [12]:
import pandas as pd
import os

for file in os.listdir(folder):
    if file.endswith(".csv"):
        print("=" * 60)
        print(file)

        df = pd.read_csv(os.path.join(folder, file))

        print(df.shape)
        print(df.columns.tolist())
        print(df.head(3))
print(folder)
print(os.path.exists(folder))

============================================================
referees.csv
(28, 4)
['referee_id', 'name', 'country', 'avg_cards_per_game']
   referee_id              name  country  avg_cards_per_game
0           1  Szymon Marciniak   Poland                 4.2
1           2    Daniele Orsato    Italy                 4.8
2           3    Michael Oliver  England                 3.9
============================================================
match_lineups.csv
(5408, 7)
['lineup_id', 'match_id', 'player_id', 'team_id', 'is_starting_xi', 'tactical_position', 'minutes_played']
   lineup_id  match_id  player_id  team_id  is_starting_xi tactical_position  \
0          1         1          1        1               1                GK
1          2         1          2        1               0               DEF
2          3         1          3        1               1               DEF

   minutes_played
0              90
1               0
2              90
============================================================
venues.csv
(16, 8)
['venue_id', 'stadium_name', 'city', 'country', 'capacity', 'latitude', 'longitude', 'elevation_meters']
   venue_id                                   stadium_name             city  \
0         1           Mexico City Stadium (Estadio Azteca)      Mexico City
1         2  New York New Jersey Stadium (MetLife Stadium)  East Rutherford
2         3             Los Angeles Stadium (SoFi Stadium)        Inglewood

  country  capacity  latitude  longitude  elevation_meters
0     MEX     80824   19.3031   -99.1506              2200
1     USA     82500   40.8136   -74.0744                 7
2     USA     70240   33.9535  -118.3390                30
============================================================
tournament_stages.csv
(7, 3)
['stage_id', 'stage_name', 'is_knockout']
   stage_id   stage_name  is_knockout
0         1  Group Stage        False
1         2  Round of 32         True
2         3  Round of 16         True
============================================================
player_stats.csv
(1248, 21)
['player_id', 'player_name', 'team_id', 'position', 'matches_played', 'matches_started', 'minutes_played', 'goals', 'assists', 'shots', 'shots_on_target', 'yellow_cards', 'red_cards', 'penalty_goals', 'own_goals', 'clean_sheets', 'saves', 'goals_conceded', 'average_rating', 'data_source', 'last_verified']
   player_id            player_name  team_id position  matches_played  \
0          1       José Raúl Rangel        1       GK               5
1          2  Jorge Eduardo Sanchez        1      DEF               4
2          3     César Jasib Montes        1      DEF               4

   matches_started  minutes_played  goals  assists  shots  ...  yellow_cards  \
0                5             438      0        0    NaN  ...             0
1                4             349      0        1    NaN  ...             1
2                4             315      0        0    NaN  ...             0

   red_cards  penalty_goals  own_goals  clean_sheets  saves  goals_conceded  \
0          0              0          0           4.0    7.0             3.0
1          0              0          0           NaN    NaN             NaN
2          1              0          0           NaN    NaN             NaN

   average_rating    data_source last_verified
0             NaN  sofascore.com    2026-07-19
1             NaN  sofascore.com    2026-07-19
2             NaN  sofascore.com    2026-07-19

[3 rows x 21 columns]
============================================================
squads_and_players.csv
(1248, 10)
['player_id', 'team_id', 'player_name', 'position', 'club_team', 'market_value_eur', 'caps', 'date_of_birth', 'height_cm', 'goals']
   player_id  team_id            player_name position            club_team  \
0          1        1       José Raúl Rangel       GK       CD Guadalajara
1          2        1  Jorge Eduardo Sanchez      DEF        PAOK Saloniki
2          3        1     César Jasib Montes      DEF  FC Lokomotiv Moscow

   market_value_eur  caps date_of_birth  height_cm  goals
0           8933646    15    2000-02-25        190      0
1          24628639    59    1997-12-10        176      3
2          10912552    69    1997-02-24        191      4
============================================================
match_team_stats.csv
(208, 12)
['match_id', 'team_id', 'possession_pct', 'total_shots', 'shots_on_target', 'corners', 'fouls', 'offsides', 'saves', 'player_of_the_match', 'data_source', 'last_updated']
   match_id  team_id  possession_pct  total_shots  shots_on_target  corners  \
0         1        1              57           16                4        6
1         1        2              43            3                2        3
2         2        3              54           12                5        4

   fouls  offsides  saves     player_of_the_match    data_source last_updated
0     11         2      1  Julián Andrés Quinones       fifa.com   2026-06-24
1     15         1      4                     NaN       fifa.com   2026-06-24
2     10         1      2            Inbeom Hwang  sofascore.com   2026-06-24
============================================================
teams.csv
(48, 8)
['team_id', 'team_name', 'fifa_code', 'group_letter', 'confederation', 'fifa_ranking_pre_tournament', 'elo_rating', 'manager_name']
   team_id     team_name fifa_code group_letter confederation  \
0        1        Mexico       MEX            A      CONCACAF
1        2  South Africa       RSA            A           CAF
2        3   South Korea       KOR            A           AFC

   fifa_ranking_pre_tournament  elo_rating    manager_name
0                           14        1810  Javier Aguirre
1                           60        1620      Hugo Broos
2                           22        1800   Hong Myung-bo
============================================================
match_events.csv
(834, 6)
['event_id', 'match_id', 'minute', 'event_type', 'team_id', 'player_id']
   event_id  match_id minute   event_type  team_id  player_id
0         1         1     17  Yellow Card        2         30
1         2         1     23  Yellow Card        1         26
2         3         1     55     Red Card        2         39
============================================================
matches.csv
(104, 17)
['match_id', 'date', 'kickoff_time_utc', 'stage_id', 'venue_id', 'home_team_id', 'away_team_id', 'home_score', 'away_score', 'home_penalty_score', 'away_penalty_score', 'status', 'result_type', 'home_xg', 'away_xg', 'referee_id', 'player_of_the_match_id']
   match_id        date kickoff_time_utc  stage_id  venue_id  home_team_id  \
0         1  2026-06-11            19:00         1         1             1
1         2  2026-06-11            23:00         1         7             3
2         3  2026-06-12            19:00         1         6             5

   away_team_id  home_score  away_score  home_penalty_score  \
0             2           2           0                 NaN
1             4           2           1                 NaN
2             6           1           1                 NaN

   away_penalty_score     status result_type  home_xg  away_xg  referee_id  \
0                 NaN  Completed     Regular     1.84     0.52           1
1                 NaN  Completed     Regular     1.45     1.12           2
2                 NaN  Completed     Regular     1.35     0.98           3

   player_of_the_match_id
0                      16
1                      58
2                     112
============================================================
matches_detailed.csv
(104, 23)
['match_id', 'date', 'kickoff_time_utc', 'stage_name', 'stadium_name', 'city', 'country', 'home_team_name', 'home_fifa_code', 'away_team_name', 'away_fifa_code', 'home_score', 'away_score', 'home_penalty_score', 'away_penalty_score', 'status', 'result_type', 'home_xg', 'away_xg', 'home_goalkeeper', 'away_goalkeeper', 'player_of_the_match_name', 'referee_name']
   match_id        date kickoff_time_utc   stage_name  \
0         1  2026-06-11            19:00  Group Stage
1         2  2026-06-11            23:00  Group Stage
2         3  2026-06-12            19:00  Group Stage

                           stadium_name         city country home_team_name  \
0  Mexico City Stadium (Estadio Azteca)  Mexico City     MEX         Mexico
1   Guadalajara Stadium (Estadio Akron)      Zapopan     MEX    South Korea
2           Toronto Stadium (BMO Field)      Toronto     CAN         Canada

  home_fifa_code          away_team_name  ... home_penalty_score  \
0            MEX            South Africa  ...                NaN
1            KOR                 Czechia  ...                NaN
2            CAN  Bosnia and Herzegovina  ...                NaN

   away_penalty_score     status  result_type  home_xg away_xg  \
0                 NaN  Completed      Regular     1.84    0.52
1                 NaN  Completed      Regular     1.45    1.12
2                 NaN  Completed      Regular     1.35    0.98

    home_goalkeeper         away_goalkeeper    player_of_the_match_name  \
0  José Raúl Rangel  Ronwen Hayden Williams      Julián Andrés Quinones
1      Seunggyu Kim           Mat ě j Kovar                Inbeom Hwang
2    Maxime Crepeau           Nikola Vasilj  Ismaël Kenneth Jordan Kone

       referee_name
0  Szymon Marciniak
1    Daniele Orsato
2    Michael Oliver

[3 rows x 23 columns]
============================================================
match_prediction_features.csv
(104, 66)
['match_id', 'date', 'kickoff_time_utc', 'stage_id', 'is_knockout', 'home_team_id', 'home_team_name', 'home_fifa_code', 'home_confederation', 'away_team_id', 'away_team_name', 'away_fifa_code', 'away_confederation', 'venue_id', 'stadium_name', 'venue_city', 'venue_country', 'venue_capacity', 'venue_elevation_meters', 'referee_id', 'referee_name', 'referee_avg_cards', 'home_fifa_rank', 'away_fifa_rank', 'home_elo', 'away_elo', 'home_is_host', 'away_is_host', 'home_squad_avg_age', 'away_squad_avg_age', 'home_squad_total_caps', 'away_squad_total_caps', 'home_squad_total_value_eur', 'away_squad_total_value_eur', 'home_squad_avg_value_eur', 'away_squad_avg_value_eur', 'home_rest_days', 'away_rest_days', 'home_prev_avg_goals_scored', 'home_prev_avg_goals_conceded', 'away_prev_avg_goals_scored', 'away_prev_avg_goals_conceded', 'home_prev_avg_possession', 'away_prev_avg_possession', 'home_prev_avg_shots', 'away_prev_avg_shots', 'home_prev_avg_shots_on_target', 'away_prev_avg_shots_on_target', 'home_prev_avg_saves', 'away_prev_avg_saves', 'home_prev_avg_corners', 'away_prev_avg_corners', 'home_prev_avg_fouls', 'away_prev_avg_fouls', 'home_prev_avg_offsides', 'away_prev_avg_offsides', 'home_prev_avg_xg_scored', 'home_prev_avg_xg_conceded', 'away_prev_avg_xg_scored', 'away_prev_avg_xg_conceded', 'home_score', 'away_score', 'result_type', 'home_xg', 'away_xg', 'match_result']
   match_id        date kickoff_time_utc  stage_id  is_knockout  home_team_id  \
0         1  2026-06-11            19:00         1            0             1
1         2  2026-06-11            23:00         1            0             3
2         3  2026-06-12            19:00         1            0             5

  home_team_name home_fifa_code home_confederation  away_team_id  ...  \
0         Mexico            MEX           CONCACAF             2  ...
1    South Korea            KOR                AFC             4  ...
2         Canada            CAN           CONCACAF             6  ...

  home_prev_avg_xg_scored home_prev_avg_xg_conceded away_prev_avg_xg_scored  \
0                     1.3                       1.3                     1.3
1                     1.3                       1.3                     1.3
2                     1.3                       1.3                     1.3

   away_prev_avg_xg_conceded home_score away_score result_type  home_xg  \
0                        1.3          2          0     Regular     1.84
1                        1.3          2          1     Regular     1.45
2                        1.3          1          1     Regular     1.35

   away_xg  match_result
0     0.52             H
1     1.12             H
2     0.98             D

[3 rows x 66 columns]
FIFA_Data/data/raw
True

In [21]:
player_df = pd.read_csv("FIFA_Data/data/raw/player_stats.csv")

player_df.info()
player_df.head()
player_df.isnull().sum()
player_df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1248 entries, 0 to 1247
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   player_id        1248 non-null   int64
 1   player_name      1248 non-null   object
 2   team_id          1248 non-null   int64
 3   position         1248 non-null   object
 4   matches_played   1248 non-null   int64
 5   matches_started  1248 non-null   int64
 6   minutes_played   1248 non-null   int64
 7   goals            1248 non-null   int64
 8   assists          1248 non-null   int64
 9   shots            0 non-null      float64
 10  shots_on_target  0 non-null      float64
 11  yellow_cards     1248 non-null   int64
 12  red_cards        1248 non-null   int64
 13  penalty_goals    1248 non-null   int64
 14  own_goals        1248 non-null   int64
 15  clean_sheets     145 non-null    float64
 16  saves            145 non-null    float64
 17  goals_conceded   145 non-null    float64
 18  average_rating   0 non-null      float64
 19  data_source      1035 non-null   object
 20  last_verified    1248 non-null   object
dtypes: float64(6), int64(11), object(4)
memory usage: 204.9+ KB

np.int64(0)

In [22]:
player_df.drop(
    columns=["shots", "shots_on_target", "average_rating"],
    inplace=True
)

In [24]:
player_df["last_verified"] = pd.to_datetime(
    player_df["last_verified"],
    errors="coerce"
)

In [26]:
player_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1248 entries, 0 to 1247
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   player_id        1248 non-null   int64
 1   player_name      1248 non-null   object
 2   team_id          1248 non-null   int64
 3   position         1248 non-null   object
 4   matches_played   1248 non-null   int64
 5   matches_started  1248 non-null   int64
 6   minutes_played   1248 non-null   int64
 7   goals            1248 non-null   int64
 8   assists          1248 non-null   int64
 9   yellow_cards     1248 non-null   int64
 10  red_cards        1248 non-null   int64
 11  penalty_goals    1248 non-null   int64
 12  own_goals        1248 non-null   int64
 13  clean_sheets     145 non-null    float64
 14  saves            145 non-null    float64
 15  goals_conceded   145 non-null    float64
 16  data_source      1035 non-null   object
 17  last_verified    1248 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(11), object(3)
memory usage: 175.6+ KB

In [27]:
player_df.head()

,player_id,player_name,team_id,position,matches_played,matches_started,minutes_played,goals,assists,yellow_cards,red_cards,penalty_goals,own_goals,clean_sheets,saves,goals_conceded,data_source,last_verified
0,1,José Raúl Rangel,1,GK,5,5,438,0,0,0,0,0,0,4.0,7.0,3.0,sofascore.com,2026-07-19
1,2,Jorge Eduardo Sanchez,1,DEF,4,4,349,0,1,1,0,0,0,NaN,NaN,NaN,sofascore.com,2026-07-19
2,3,César Jasib Montes,1,DEF,4,4,315,0,0,0,1,0,0,NaN,NaN,NaN,sofascore.com,2026-07-19
3,4,Edson Omar Alvarez,1,DEF,4,2,239,0,0,1,0,0,0,NaN,NaN,NaN,sofascore.com,2026-07-19
4,5,Johan Felipe Vasquez,1,DEF,4,4,360,0,0,1,0,0,0,NaN,NaN,NaN,sofascore.com,2026-07-19

In [32]:
os.makedirs("processed", exist_ok=True)

In [70]:
player_df.to_csv("processed/player_stats_clean.csv", index=False)
os.listdir("processed")

['player_stats_clean.csv']

In [58]:
teams_df = pd.read_csv(r"FIFA_Data/data/raw/teams.csv")
teams_df.head()
teams_df.columns
teams_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   team_id                      48 non-null     int64
 1   team_name                    48 non-null     object
 2   fifa_code                    48 non-null     object
 3   group_letter                 48 non-null     object
 4   confederation                48 non-null     object
 5   fifa_ranking_pre_tournament  48 non-null     int64
 6   elo_rating                   48 non-null     int64
 7   manager_name                 48 non-null     object
dtypes: int64(3), object(5)
memory usage: 3.1+ KB

In [60]:
teams_df.isnull().sum()
teams_df.duplicated().sum()

np.int64(0)

In [61]:
teams_df["team_name"].unique()

array(['Mexico', 'South Africa', 'South Korea', 'Czechia', 'Canada',
       'Bosnia and Herzegovina', 'Qatar', 'Switzerland', 'Brazil',
       'Morocco', 'Haiti', 'Scotland', 'USA', 'Paraguay', 'Australia',
       'Türkiye', 'Germany', 'Curaçao', "Côte d'Ivoire", 'Ecuador',
       'Netherlands', 'Japan', 'Sweden', 'Tunisia', 'Belgium', 'Egypt',
       'IR Iran', 'New Zealand', 'Spain', 'Cabo Verde', 'Saudi Arabia',
       'Uruguay', 'France', 'Senegal', 'Iraq', 'Norway', 'Argentina',
       'Algeria', 'Austria', 'Jordan', 'Portugal', 'Congo DR',
       'Uzbekistan', 'Colombia', 'England', 'Croatia', 'Ghana', 'Panama'],
      dtype=object)

In [62]:
teams_df.columns = (
    teams_df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

In [64]:
teams_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   team_id                      48 non-null     int64
 1   team_name                    48 non-null     object
 2   fifa_code                    48 non-null     object
 3   group_letter                 48 non-null     object
 4   confederation                48 non-null     object
 5   fifa_ranking_pre_tournament  48 non-null     int64
 6   elo_rating                   48 non-null     int64
 7   manager_name                 48 non-null     object
dtypes: int64(3), object(5)
memory usage: 3.1+ KB

In [65]:
teams_df.head()

,team_id,team_name,fifa_code,group_letter,confederation,fifa_ranking_pre_tournament,elo_rating,manager_name
0,1,Mexico,MEX,A,CONCACAF,14,1810,Javier Aguirre
1,2,South Africa,RSA,A,CAF,60,1620,Hugo Broos
2,3,South Korea,KOR,A,AFC,22,1800,Hong Myung-bo
3,4,Czechia,CZE,A,UEFA,40,1740,Miroslav Koubek
4,5,Canada,CAN,B,CONCACAF,33,1795,Jesse Marsch

In [73]:
os.makedirs("FIFA_Data/processed", exist_ok=True)

teams_df.to_csv(
    "processed/teams_clean.csv",
    index=False
)
os.listdir("processed")

['player_stats_clean.csv', 'teams_clean.csv']

In [76]:
matches_df = pd.read_csv(r"FIFA_Data/data/raw/matches.csv")
matches_df.head()
matches_df.columns
matches_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   match_id                104 non-null    int64
 1   date                    104 non-null    object
 2   kickoff_time_utc        104 non-null    object
 3   stage_id                104 non-null    int64
 4   venue_id                104 non-null    int64
 5   home_team_id            104 non-null    int64
 6   away_team_id            104 non-null    int64
 7   home_score              104 non-null    int64
 8   away_score              104 non-null    int64
 9   home_penalty_score      4 non-null      float64
 10  away_penalty_score      4 non-null      float64
 11  status                  104 non-null    object
 12  result_type             104 non-null    object
 13  home_xg                 104 non-null    float64
 14  away_xg                 104 non-null    float64
 15  referee_id              104 non-null    int64
 16  player_of_the_match_id  104 non-null    int64
dtypes: float64(4), int64(9), object(4)
memory usage: 13.9+ KB

In [77]:
matches_df.isnull().sum()

match_id                    0
date                        0
kickoff_time_utc            0
stage_id                    0
venue_id                    0
home_team_id                0
away_team_id                0
home_score                  0
away_score                  0
home_penalty_score        100
away_penalty_score        100
status                      0
result_type                 0
home_xg                     0
away_xg                     0
referee_id                  0
player_of_the_match_id      0
dtype: int64

In [79]:
matches_df["home_penalty_score"] = (
    matches_df["home_penalty_score"]
    .fillna(0)
    .astype(int)
)

matches_df["away_penalty_score"] = (
    matches_df["away_penalty_score"]
    .fillna(0)
    .astype(int)
)

In [80]:
matches_df.isnull().sum()

match_id                  0
date                      0
kickoff_time_utc          0
stage_id                  0
venue_id                  0
home_team_id              0
away_team_id              0
home_score                0
away_score                0
home_penalty_score        0
away_penalty_score        0
status                    0
result_type               0
home_xg                   0
away_xg                   0
referee_id                0
player_of_the_match_id    0
dtype: int64

In [81]:
matches_df["date"] = pd.to_datetime(matches_df["date"])

In [82]:
matches_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   match_id                104 non-null    int64
 1   date                    104 non-null    datetime64[ns]
 2   kickoff_time_utc        104 non-null    object
 3   stage_id                104 non-null    int64
 4   venue_id                104 non-null    int64
 5   home_team_id            104 non-null    int64
 6   away_team_id            104 non-null    int64
 7   home_score              104 non-null    int64
 8   away_score              104 non-null    int64
 9   home_penalty_score      104 non-null    int64
 10  away_penalty_score      104 non-null    int64
 11  status                  104 non-null    object
 12  result_type             104 non-null    object
 13  home_xg                 104 non-null    float64
 14  away_xg                 104 non-null    float64
 15  referee_id              104 non-null    int64
 16  player_of_the_match_id  104 non-null    int64
dtypes: datetime64[ns](1), float64(2), int64(11), object(3)
memory usage: 13.9+ KB

In [83]:
os.makedirs("FIFA_Data/processed", exist_ok=True)

matches_df.to_csv(
    "processed/matches_clean.csv",
    index=False
)
os.listdir("processed")

['matches_clean.csv', 'player_stats_clean.csv', 'teams_clean.csv']

In [85]:
matches_lineups_df = pd.read_csv(r"FIFA_Data/data/raw/match_lineups.csv")
matches_lineups_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5408 entries, 0 to 5407
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lineup_id          5408 non-null   int64
 1   match_id           5408 non-null   int64
 2   player_id          5408 non-null   int64
 3   team_id            5408 non-null   int64
 4   is_starting_xi     5408 non-null   int64
 5   tactical_position  5408 non-null   object
 6   minutes_played     5408 non-null   int64
dtypes: int64(6), object(1)
memory usage: 295.9+ KB

In [86]:
matches_lineups_df.isnull().sum()

lineup_id            0
match_id             0
player_id            0
team_id              0
is_starting_xi       0
tactical_position    0
minutes_played       0
dtype: int64

In [87]:
matches_lineups_df.duplicated().sum()

np.int64(0)

In [88]:
matches_lineups_df["tactical_position"].unique()

array(['GK', 'DEF', 'MID', 'FWD'], dtype=object)

In [90]:
matches_lineups_df["tactical_position"] = (
    matches_lineups_df["tactical_position"]
    .str.strip()
    .str.upper()
)

In [91]:
matches_lineups_df["is_starting_xi"].value_counts()

is_starting_xi
0    3120
1    2288
Name: count, dtype: int64

In [92]:
os.makedirs("FIFA_Data/processed", exist_ok=True)

matches_lineups_df.to_csv(
    "processed/lineups_clean.csv",
    index=False
)
os.listdir("processed")

['matches_clean.csv',
 'player_stats_clean.csv',
 'teams_clean.csv',
 'lineups_clean.csv']

In [94]:
squads_and_players = pd.read_csv(r"FIFA_Data/data/raw/squads_and_players.csv")
squads_and_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1248 entries, 0 to 1247
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         1248 non-null   int64
 1   team_id           1248 non-null   int64
 2   player_name       1248 non-null   object
 3   position          1248 non-null   object
 4   club_team         1248 non-null   object
 5   market_value_eur  1248 non-null   int64
 6   caps              1248 non-null   int64
 7   date_of_birth     1248 non-null   object
 8   height_cm         1248 non-null   int64
 9   goals             1248 non-null   int64
dtypes: int64(6), object(4)
memory usage: 97.6+ KB

In [95]:
squads_and_players.isnull().sum()

player_id           0
team_id             0
player_name         0
position            0
club_team           0
market_value_eur    0
caps                0
date_of_birth       0
height_cm           0
goals               0
dtype: int64

In [96]:
squads_and_players.duplicated().sum()

np.int64(0)

In [97]:
squads_and_players["date_of_birth"] = pd.to_datetime(
    squads_and_players["date_of_birth"]
)

In [98]:
text_cols = ["player_name", "position", "club_team"]

for col in text_cols:
    squads_and_players[col] = squads_and_players[col].str.strip()

In [99]:
numeric_cols = [
    "market_value_eur",
    "caps",
    "height_cm",
    "goals"
]

(squads_and_players[numeric_cols] < 0).sum()

market_value_eur    0
caps                0
height_cm           0
goals               0
dtype: int64

In [100]:
squads_and_players.to_csv(
    "processed/squads_and_players_clean.csv",
    index=False
)
os.listdir("processed")

['matches_clean.csv',
 'player_stats_clean.csv',
 'teams_clean.csv',
 'squads_and_players_clean.csv',
 'lineups_clean.csv']

In [102]:
match_tea_sta= pd.read_csv(r"FIFA_Data/data/raw/match_team_stats.csv")
match_tea_sta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   match_id             208 non-null    int64
 1   team_id              208 non-null    int64
 2   possession_pct       208 non-null    int64
 3   total_shots          208 non-null    int64
 4   shots_on_target      208 non-null    int64
 5   corners              208 non-null    int64
 6   fouls                208 non-null    int64
 7   offsides             208 non-null    int64
 8   saves                208 non-null    int64
 9   player_of_the_match  105 non-null    object
 10  data_source          208 non-null    object
 11  last_updated         208 non-null    object
dtypes: int64(9), object(3)
memory usage: 19.6+ KB

In [103]:
match_tea_sta.isnull().sum()

match_id                 0
team_id                  0
possession_pct           0
total_shots              0
shots_on_target          0
corners                  0
fouls                    0
offsides                 0
saves                    0
player_of_the_match    103
data_source              0
last_updated             0
dtype: int64

In [104]:
match_tea_sta["player_of_the_match"] = (
    match_tea_sta["player_of_the_match"]
    .fillna("Unknown")
)

In [105]:
match_tea_sta.isnull().sum()

match_id               0
team_id                0
possession_pct         0
total_shots            0
shots_on_target        0
corners                0
fouls                  0
offsides               0
saves                  0
player_of_the_match    0
data_source            0
last_updated           0
dtype: int64

In [106]:
match_tea_sta["last_updated"] = pd.to_datetime(
    match_tea_sta["last_updated"]
)

In [107]:
match_tea_sta["data_source"] = (
    match_tea_sta["data_source"]
    .str.strip()
)

match_tea_sta["player_of_the_match"] = (
    match_tea_sta["player_of_the_match"]
    .str.strip()
)

In [109]:
match_tea_sta.duplicated().sum()

np.int64(0)

In [110]:
match_tea_sta.to_csv(
    "processed/team_match_stats_clean.csv",
    index=False
)
os.listdir("processed")

['matches_clean.csv',
 'player_stats_clean.csv',
 'team_match_stats_clean.csv',
 'teams_clean.csv',
 'squads_and_players_clean.csv',
 'lineups_clean.csv']

In [112]:
!zip -r processed.zip processed
files.download("processed.zip")

updating: processed/ (stored 0%)
updating: processed/matches_clean.csv (deflated 72%)
updating: processed/player_stats_clean.csv (deflated 74%)
updating: processed/team_match_stats_clean.csv (deflated 70%)
updating: processed/teams_clean.csv (deflated 36%)
updating: processed/squads_and_players_clean.csv (deflated 57%)
updating: processed/lineups_clean.csv (deflated 72%)